name: Deploy to GitHub Pages

on:
  workflow_call:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  markdown-components:
    name: markdown-modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: scilus/nf-neuro
          ref: main
          path: nf-neuro
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.10"
          cache: pip
      - name: Install dependencies
        run: |
          pip install pyyaml
      - name: Generate markdown
        id: generate-module
        run: |
          shopt -s globstar
          function convert_module () {
            local file="$1"
            local module_name=$(basename "$(dirname "$file")")
            local category=$(basename "$(dirname "$(dirname "$file")")")
            python nf-neuro/docs/astro/convert_module.py $file ${{ github.sha }} modules/${category}_${module_name}.md
          }
          function convert_subworkflow () {
            local file="$1"
            local sbwf_name=$(basename "$(dirname "$file")")
            python nf-neuro/docs/astro/convert_subworkflow.py $file ${{ github.sha }} subworkflows/${sbwf_name}.md
          }
          export -f convert_module
          export -f convert_subworkflow

          mkdir -p modules/ subworkflows/
          parallel --jobs $(nproc) convert_module ::: nf-neuro/modules/nf-neuro/**/meta.yml
          parallel --jobs $(nproc) convert_subworkflow ::: nf-neuro/subworkflows/nf-neuro/**/meta.yml
      - name: Pack into artifact
        uses: actions/upload-artifact@v4
        with:
          name: markdown
          path: |
            modules/
            subworkflows/

  build:
    needs: markdown-components
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website code
        uses: actions/checkout@v4
        with:
          repository: scilus/nf-neuro-documentation

      - name: Download components markdown
        uses: actions/download-artifact@v4
        with:
          name: markdown
          path: src/content/docs/api/

      - name: Install, build, and upload your site
        uses: withastro/action@v2
        with:
          node-version: 22
          package-manager: npm@latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
